name: Build PR Content

# Runs on PRs from forks and same-repo - NO SECRETS
on:
  pull_request:
    types: [opened, synchronize, reopened]
  # If you want to build PRs from forks, you need to use pull_request_target
  pull_request_target:
    types: [opened, synchronize, reopened]
  push:
    branches: [main]  # Also run when PRs are merged to main
  workflow_dispatch:  # Allow manual build to kick off upload flow

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          # Use PR head SHA if triggered by pull_request, otherwise use default (push event)
          ref: ${{ github.event.pull_request.head.sha || github.sha }}

      # Your build steps here (example)
      - name: Build
        run: |
          npm install
          npm run build

      # Use the action in BUILD mode (default, no secrets needed)
      # The action automatically saves PR metadata and generates artifact names
      - name: Build CAR file
        id: build
        uses: sgtpooki/filecoin-upload-action@main  # Replace with actual version
        with:
          # mode: build is the default, but can be specified explicitly
          path: dist
